# Generated by Django 4.0.4 on 2022-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('in stock', 'В наличии'), ('out of stock', 'Нет в наличии')], max_length=20),
        ),
    ]
