# Generated by Django 4.0.4 on 2022-04-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
