# Generated by Django 4.0.4 on 2022-04-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_name_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
